// 📦 generated by copyrc. DO NOT EDIT.
// ℹ️ see .copyrc.lock for more details.

package vscode

import _ "embed"

//go:embed vscode.tar.gz
var Data []byte

// Metadata about the downloaded repository
var (
	Ref        = "tags/1.96.4"
	Commit     = "cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba"
	Repository = "github.com/microsoft/vscode"
	Permalink  = "https://github.com/microsoft/vscode/archive/refs/tags/1.96.4.tar.gz"
	Downloaded = "2025-02-05T13:59:10Z"
)
