// 📦 originally copied by copyrc
// 🔗 source: https://raw.githubusercontent.com/omissis/go-jsonschema/442a4c100c62a7d8543d1a7ab7052397057add86/tests/data/core/dateTime/dateTime.go
// 📝 license: MIT
// ℹ️ see .copyrc.lock for more details

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package testdata

import "encoding/json"
import "fmt"
import "time"

type DateTime struct {
	// MyObject corresponds to the JSON schema field "myObject".
	MyObject *DateTimeMyObject `json:"myObject,omitempty" yaml:"myObject,omitempty" mapstructure:"myObject,omitempty"`
}

type DateTimeMyObject struct {
	// MyDateTime corresponds to the JSON schema field "myDateTime".
	MyDateTime time.Time `json:"myDateTime" yaml:"myDateTime" mapstructure:"myDateTime"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DateTimeMyObject) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["myDateTime"]; raw != nil && !ok {
		return fmt.Errorf("field myDateTime in DateTimeMyObject: required")
	}
	type Plain DateTimeMyObject
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = DateTimeMyObject(plain)
	return nil
}
