# 📦 copyrc configuration file

# Source repository configuration
provider:
    repo: "golang/example" # Public Go examples repository
    ref: "master" # Branch or tag to copy from
    path: "hello" # Path within the repository

# Destination path for copied files
destination: "./output"

# Copy options
copy:
    # Files to ignore
    ignore_patterns:
        - "*.tmp"
        - "*.log"
        - ".git/*"

    # Text replacements to apply
    replacements:
        - old: "fmt"
          new: "log"
        - old: "Hello"
          new: "Greetings"
          file: "hello.go" # Only apply to specific file

# Clean up options
clean: false # Keep copied files
