inpackage: false
with-expecter: true
testonly: false
exported: true
dir: gen/mockery
outpkg: mockery
resolve-type-alias: true
issue-845-fix: true
filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go"
mockname: Mock{{.InterfaceName}}_{{.PackageName}}
packages:
    github.com/walteh/copyrc/refactor-attempt-1/provider:
        interfaces:
            Provider: {}

    github.com/walteh/copyrc/refactor-attempt-1/status:
        interfaces:
            FileFormatter: {}

    github.com/walteh/copyrc/pkg/remote:
        interfaces:
            FileFormatter:
                config:
                    with-expecter: true
            GitHubClient:
                config:
                    with-expecter: true
            Provider:
                config:
                    with-expecter: true
            RawTextFile:
                config:
                    with-expecter: true
            Release:
                config:
                    with-expecter: true
            Repository:
                config:
                    with-expecter: true

    github.com/walteh/copyrc/pkg/remote/github:
        interfaces:
            GitHubClient: {}

    github.com/walteh/copyrc/pkg/state:
        interfaces:
            StateManager:
                config:
                    with-expecter: true
