inpackage: false
with-expecter: true
testonly: false
exported: true
dir: gen/mockery
outpkg: mockery
resolve-type-alias: true
issue-845-fix: true
filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go"
mockname: Mock{{.InterfaceName}}_{{.PackageName}}
packages:
    github.com/walteh/copyrc/refactor-attempt-1/provider:
        interfaces:
            Provider: {}

    github.com/walteh/copyrc/refactor-attempt-1/status:
        interfaces:
            FileFormatter: {}
