// 📦 originally copied by copyrc
// 🔗 source: https://raw.githubusercontent.com/omissis/go-jsonschema/442a4c100c62a7d8543d1a7ab7052397057add86/tests/data/core/ip/ip.go
// 📝 license: MIT
// ℹ️ see .copyrc.lock for more details

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package testdata

import "encoding/json"
import "fmt"
import "net/netip"

type Ip struct {
	// MyObject corresponds to the JSON schema field "myObject".
	MyObject *IpMyObject `json:"myObject,omitempty" yaml:"myObject,omitempty" mapstructure:"myObject,omitempty"`
}

type IpMyObject struct {
	// MyIp corresponds to the JSON schema field "myIp".
	MyIp netip.Addr `json:"myIp" yaml:"myIp" mapstructure:"myIp"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IpMyObject) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["myIp"]; raw != nil && !ok {
		return fmt.Errorf("field myIp in IpMyObject: required")
	}
	type Plain IpMyObject
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = IpMyObject(plain)
	return nil
}
