// 📦 originally copied by copyrc
// 🔗 source: https://raw.githubusercontent.com/omissis/go-jsonschema/442a4c100c62a7d8543d1a7ab7052397057add86/tests/data/misc/tags/tags.go
// 📝 license: MIT
// ℹ️ see .copyrc.lock for more details

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package testdata

type Tags struct {
	// Html corresponds to the JSON schema field "html".
	Html *string `yaml:"html,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *string `yaml:"id,omitempty"`

	// Url corresponds to the JSON schema field "url".
	Url *string `yaml:"url,omitempty"`
}
