// 📦 originally copied by copyrc
// 🔗 source: https://raw.githubusercontent.com/omissis/go-jsonschema/442a4c100c62a7d8543d1a7ab7052397057add86/tests/data/crossPackageNoOutput/schema/schema.go
// 📝 license: MIT
// ℹ️ see .copyrc.lock for more details

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import other "github.com/atombender/go-jsonschema/tests/helpers/other"

type Schema struct {
	// DefInOtherSchema corresponds to the JSON schema field "defInOtherSchema".
	DefInOtherSchema *other.Thing `json:"defInOtherSchema,omitempty" yaml:"defInOtherSchema,omitempty" mapstructure:"defInOtherSchema,omitempty"`

	// DefInSameSchema corresponds to the JSON schema field "defInSameSchema".
	DefInSameSchema *Thing `json:"defInSameSchema,omitempty" yaml:"defInSameSchema,omitempty" mapstructure:"defInSameSchema,omitempty"`
}

type Thing struct {
	// S corresponds to the JSON schema field "s".
	S *string `json:"s,omitempty" yaml:"s,omitempty" mapstructure:"s,omitempty"`
}
