// 📦 originally copied by copyrc
// 🔗 source: https://raw.githubusercontent.com/omissis/go-jsonschema/442a4c100c62a7d8543d1a7ab7052397057add86/tests/data/crossPackageNoOutput/other/other.go
// 📝 license: MIT
// ℹ️ see .copyrc.lock for more details

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package testdata

type Thing struct {
	// S corresponds to the JSON schema field "s".
	S *string `json:"s,omitempty" yaml:"s,omitempty" mapstructure:"s,omitempty"`
}
