// 📦 Generated by copyrc. DO NOT EDIT.
// 🔗 Source: golang/example
// ℹ️ See .copyrc.lock for more details.

// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package reverse_test

import (
	"log"

	"golang.org/x/example/hello/reverse"
)

func ExampleString() {
	log.Println(reverse.String("hello"))
	// Output: olleh
}
