// 📦 originally copied by copyrc
// 🔗 source: https://raw.githubusercontent.com/omissis/go-jsonschema/442a4c100c62a7d8543d1a7ab7052397057add86/tests/data/schemaExtensions/nonNillable/nillability.go
// 📝 license: MIT
// ℹ️ see .copyrc.lock for more details

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package testdata

type Nillability struct {
	// Name corresponds to the JSON schema field "name".
	Name *map[bool]string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}
